version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db  # Updated to use the db service
      - DB_POSTGRESDB_PORT=5432  # Standard PostgreSQL port
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - intro-network

  nessie:
    image: projectnessie/nessie:0.76.6
    container_name: nessie
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=19120
      - QUARKUS_LOG_LEVEL=INFO
      - OTEL_TRACES_EXPORTER=none
      - nessie.version.store.type=MONGODB
      - quarkus.mongodb.connection-string=mongodb://root:password@mongo:27017
    volumes:
      - ./nessie-data:/nessie/data
    ports:
      - "19120:19120"
    networks:
      - intro-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
    networks:
      - intro-network

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/minio-data
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/datalake;
      mc mb myminio/warehouse;
      tail -f /dev/null"
    networks:
      - intro-network

  spark:
    image: alexmerced/spark35nb:spark3_5_2
    ports:
      - 8080:8080
      - 7077:7077
      - 8081:8081
      - 4040-4045:4040-4045
      - 18080:18080
      - 8888:8888
    environment:
      - AWS_REGION=us-east-1
      - SPARK_MASTER_HOST=spark
    volumes:
      - ./spark-events:/tmp/spark-events
    container_name: spark
    restart: unless-stopped
    entrypoint: >
      /bin/bash -c "
      /opt/spark/sbin/start-master.sh && \
      /opt/spark/sbin/start-worker.sh spark://localhost:7077 && \
      mkdir -p /tmp/spark-events && \
      start-history-server.sh && \
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' && \
      tail -f /dev/null"
    networks:
      - intro-network

  dremio:
    image: dremio/dremio-oss:25.1
    ports:
      - 9047:9047
      - 31010:31010
    container_name: dremio
    restart: unless-stopped
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - ./dremio-data:/opt/dremio/data
    networks:
      - intro-network

  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - intro-network

  db:
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./build/superset/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - intro-network

  superset:
    build:
      context: ./build/superset
    container_name: superset_app
    restart: unless-stopped
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    ports:
      - 8088:8088
    volumes:
      - ./build/superset/docker:/app/docker
      - ./superset_home:/app/superset_home
    networks:
      - intro-network

  superset-init:
    build:
      context: ./build/superset
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    volumes:
      - ./build/superset/docker:/app/docker
      - ./superset_home:/app/superset_home
    networks:
      - intro-network

  superset-worker:
    build:
      context: ./build/superset
    container_name: superset_worker
    restart: unless-stopped
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    volumes:
      - ./build/superset/docker:/app/docker
      - ./superset_home:/app/superset_home
    networks:
      - intro-network

  superset-worker-beat:
    build:
      context: ./build/superset
    container_name: superset_worker_beat
    restart: unless-stopped
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    volumes:
      - ./build/superset/docker:/app/docker
      - ./superset_home:/app/superset_home
    networks:
      - intro-network

  # Potentially Remove
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin
    ports:
      - "8083:80"  # Expose port 80 on the host machine to access pgAdmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com  # Default pgAdmin email
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret   # Default pgAdmin password
    restart: unless-stopped  # Automatically restart the container unless stopped manually
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin  # Add volume for persistence
    networks:
      - intro-network  # Use the existing network if needed

volumes:
  n8n_data:
  superset_home:
  db_home:
  redis:
  nessie-data:
  minio-data:
  spark-events:
  dremio-data:

networks:
  intro-network: